services:
  - type: web
    name: fpes-web
    env: docker
    plan: free

    # Path to your Dockerfile relative to the repo root
    dockerfilePath: ./Dockerfile

    # Optional: if the app is in a subdirectory, set rootDir, e.g. ./FPES
    # rootDir: ./

    # Environment variables (override these in the Render dashboard as needed)
    envVars:
  - key: APP_ENV
    value: production
  - key: DB_HOST
    value: gondola.proxy.rlwy.net
  - key: DB_PORT
    value: "48315"
  - key: DB_NAME
    value: railway
  - key: DB_USER
    value: root
  - key: DB_PASS
    value: LSWRVKbunfFrSiRRdyleUHWVjhYfzWCK